

export const CLAIM_USERS = [
    {
        "id": 43,
        "name": "Елена",
        "surname": "Дурнева",
        "patronymic": "Витальевна",
        "id_departament": 9,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 46,
        "name": "Александр",
        "surname": "Кошелев",
        "patronymic": "Станиславович",
        "id_departament": 1,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 47,
        "name": "Валентина",
        "surname": "Кошелева",
        "patronymic": "Григорьевна",
        "id_departament": 19,
        "id_company": 2,
        "boss_id": 0
    },
    {
        "id": 57,
        "name": "Дмитрий",
        "surname": "Печников",
        "patronymic": "Валерьевич",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 91,
        "name": "Сергей",
        "surname": "Фокин",
        "patronymic": "Петрович",
        "id_departament": 7,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 133,
        "name": "Виктория",
        "surname": "Друговейко",
        "patronymic": "Юрьевна",
        "id_departament": 3,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 134,
        "name": "Сергей",
        "surname": "Безбородов",
        "patronymic": "Дмитриевич",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 180,
        "name": "Леонид",
        "surname": "Александров",
        "patronymic": "Алексеевич",
        "id_departament": 9,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 198,
        "name": "Валентина",
        "surname": "Рогалева",
        "patronymic": "Евгеньевна",
        "id_departament": 15,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 226,
        "name": "Анна ",
        "surname": "Столярова",
        "patronymic": "Владимировна",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 271,
        "name": "Раджаббой ",
        "surname": "Ашуров ",
        "patronymic": "Фуркатович ",
        "id_departament": 18,
        "id_company": 2,
        "boss_id": 43
    },
    {
        "id": 272,
        "name": "Фуркат",
        "surname": "Ашуров  ",
        "patronymic": "Пардакулович ",
        "id_departament": 18,
        "id_company": 2,
        "boss_id": 43
    },
    {
        "id": 280,
        "name": "",
        "surname": "Администратор",
        "patronymic": "",
        "id_departament": 19,
        "id_company": 2,
        "boss_id": 0
    },
    {
        "id": 282,
        "name": "Руслан",
        "surname": "Шалин",
        "patronymic": "Викторович",
        "id_departament": 11,
        "id_company": 2,
        "boss_id": 282
    },
    {
        "id": 283,
        "name": "Жанна",
        "surname": "Булгакова",
        "patronymic": "Владимировна",
        "id_departament": 11,
        "id_company": 2,
        "boss_id": 282
    },
    {
        "id": 287,
        "name": "Олег",
        "surname": "Бибик",
        "patronymic": "Николаевич",
        "id_departament": 17,
        "id_company": 2,
        "boss_id": 43
    },
    {
        "id": 289,
        "name": "Геннадий",
        "surname": "Рябков",
        "patronymic": "Иванович",
        "id_departament": 17,
        "id_company": 2,
        "boss_id": 43
    },
    {
        "id": 304,
        "name": "Ирина",
        "surname": "Зеленко",
        "patronymic": "Вячеславовна",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 309,
        "name": "Александр ",
        "surname": "Бобко ",
        "patronymic": "Владимирович ",
        "id_departament": 8,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 327,
        "name": "Вячеслав",
        "surname": "Кобяков",
        "patronymic": "Борисович",
        "id_departament": 17,
        "id_company": 2,
        "boss_id": 43
    },
    {
        "id": 334,
        "name": "Мария",
        "surname": "Глинтерник",
        "patronymic": "Алексеевна",
        "id_departament": 2,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 337,
        "name": "Олег",
        "surname": "Иванов",
        "patronymic": "Рудольфович",
        "id_departament": 7,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 339,
        "name": "Ксения",
        "surname": "Горяева",
        "patronymic": "Викторовна",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 340,
        "name": "Павел",
        "surname": "Петровский",
        "patronymic": "Сергеевич",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 361,
        "name": "Иван",
        "surname": "Журба",
        "patronymic": "Анатольевич",
        "id_departament": 18,
        "id_company": 2,
        "boss_id": 43
    },
    {
        "id": 371,
        "name": "Константин",
        "surname": "Батов",
        "patronymic": "Александрович",
        "id_departament": 8,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 374,
        "name": "Евгений",
        "surname": "Котоликов",
        "patronymic": "Алексеевич",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 393,
        "name": "отдел",
        "surname": "Строительный",
        "patronymic": "",
        "id_departament": 11,
        "id_company": 2,
        "boss_id": 282
    },
    {
        "id": 400,
        "name": "Сергей",
        "surname": "Шевченко",
        "patronymic": "Витальевич",
        "id_departament": 7,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 405,
        "name": "Максим",
        "surname": "Турлов",
        "patronymic": "Георгиевич",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 411,
        "name": "Павел",
        "surname": "Мельников",
        "patronymic": "Валерьевич",
        "id_departament": 7,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 436,
        "name": "Владимир",
        "surname": "Горев",
        "patronymic": "Сергеевич",
        "id_departament": 9,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 463,
        "name": "Дмитрий",
        "surname": "Нестеренко",
        "patronymic": "Сергеевич",
        "id_departament": 11,
        "id_company": 2,
        "boss_id": 282
    },
    {
        "id": 474,
        "name": "Алексей",
        "surname": "Федянин",
        "patronymic": "Валерьевич",
        "id_departament": 14,
        "id_company": 2,
        "boss_id": 540
    },
    {
        "id": 482,
        "name": "Артём",
        "surname": "Дрюков",
        "patronymic": "Владимирович",
        "id_departament": 14,
        "id_company": 2,
        "boss_id": 540
    },
    {
        "id": 483,
        "name": "Максим",
        "surname": "Матченков",
        "patronymic": "Юрьевич",
        "id_departament": 14,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 486,
        "name": "Андрей",
        "surname": "Шаранда",
        "patronymic": "Дмитриевич",
        "id_departament": 14,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 493,
        "name": "Юрий",
        "surname": "Дегелевич",
        "patronymic": "Евгеньевич",
        "id_departament": 1,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 498,
        "name": "Ольга",
        "surname": "Булышева",
        "patronymic": "Александровна",
        "id_departament": 21,
        "id_company": 3,
        "boss_id": 46
    },
    {
        "id": 499,
        "name": "София",
        "surname": "Сорокина",
        "patronymic": "Евгеньевна",
        "id_departament": 14,
        "id_company": 2,
        "boss_id": 540
    },
    {
        "id": 521,
        "name": "Любовь",
        "surname": "Палагушина",
        "patronymic": "Владимировна",
        "id_departament": 3,
        "id_company": 2,
        "boss_id": 133
    },
    {
        "id": 522,
        "name": "Александр",
        "surname": "Степанченко",
        "patronymic": "Николаевич",
        "id_departament": 20,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 528,
        "name": "Роман",
        "surname": "Карташов",
        "patronymic": "Станиславович",
        "id_departament": 9,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 530,
        "name": "Станислав",
        "surname": "Самарин",
        "patronymic": "Александрович",
        "id_departament": 17,
        "id_company": 2,
        "boss_id": 43
    },
    {
        "id": 531,
        "name": "Анна",
        "surname": "Захарова",
        "patronymic": "Юрьевна",
        "id_departament": 3,
        "id_company": 2,
        "boss_id": 133
    },
    {
        "id": 533,
        "name": "Татьяна",
        "surname": "Балабанова",
        "patronymic": "Алексеевна",
        "id_departament": 14,
        "id_company": 2,
        "boss_id": 540
    },
    {
        "id": 536,
        "name": "Екатерина",
        "surname": "Филиппова",
        "patronymic": "Юрьевна",
        "id_departament": 15,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 537,
        "name": "Сергей",
        "surname": "Иванов",
        "patronymic": "Алексеевич",
        "id_departament": 7,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 538,
        "name": "Геннадий",
        "surname": "Бакланов",
        "patronymic": "Валентинович",
        "id_departament": 20,
        "id_company": 2,
        "boss_id": 493
    },
    {
        "id": 540,
        "name": "Лидия",
        "surname": "Точилина",
        "patronymic": "Львовна",
        "id_departament": 14,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 547,
        "name": "Геннадий",
        "surname": "Балымов",
        "patronymic": "Робертович",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 549,
        "name": "Алан",
        "surname": "Рясянен",
        "patronymic": "Раймович",
        "id_departament": 20,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 553,
        "name": "Людмила",
        "surname": "Владимирская",
        "patronymic": "Павловна",
        "id_departament": 19,
        "id_company": 2,
        "boss_id": 0
    },
    {
        "id": 555,
        "name": "Мария",
        "surname": "Ладыгина",
        "patronymic": "Владимировна",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 304
    },
    {
        "id": 556,
        "name": "Юнус",
        "surname": "Азизкулов",
        "patronymic": "Хусаинович",
        "id_departament": 18,
        "id_company": 2,
        "boss_id": 0
    },
    {
        "id": 557,
        "name": "Маруфжон",
        "surname": "Назаров",
        "patronymic": "Одилович",
        "id_departament": 18,
        "id_company": 3,
        "boss_id": 0
    },
    {
        "id": 558,
        "name": "Богдан",
        "surname": "Красников",
        "patronymic": "Юрьевич",
        "id_departament": 14,
        "id_company": 3,
        "boss_id": 0
    },
    {
        "id": 560,
        "name": "Наталия",
        "surname": "Минина",
        "patronymic": "Юрьевна",
        "id_departament": 3,
        "id_company": 3,
        "boss_id": 0
    },
    {
        "id": 562,
        "name": "Анастасия",
        "surname": "Коляскина",
        "patronymic": "Константиновна",
        "id_departament": 5,
        "id_company": 2,
        "boss_id": 46
    },
    {
        "id": 563,
        "name": "Сергей",
        "surname": "Гельмбрехт",
        "patronymic": "Сергеевич",
        "id_departament": 7,
        "id_company": 2,
        "boss_id": 0
    },
    {
        "id": 564,
        "name": "Михаил",
        "surname": "Новосёлов",
        "patronymic": "Скудович",
        "id_departament": 2,
        "id_company": 3,
        "boss_id": 0
    },
    {
        "id": 566,
        "name": "Рондо",
        "surname": "Тест",
        "patronymic": "Кузьмич",
        "id_departament": 2,
        "id_company": 3,
        "boss_id": 0
    },
    {
        "id": 567,
        "name": "Rondovec",
        "surname": "Rondov",
        "patronymic": "Grechedoll",
        "id_departament": 5,
        "id_company": 3,
        "boss_id": 0
    },
    {
        "id": 568,
        "name": "Гавриил",
        "surname": "Арчи",
        "patronymic": "Дессус",
        "id_departament": 1,
        "id_company": 3,
        "boss_id": 0
    }
];


export const CLAIM_STATES = [
    {
        "id": 1,
        "title": "",
        "text": "Не приходил в офис",
        "color": "#fefefe",
        "icon": "MinusCircleOutlined",
        "need_work": 1,
        "need_approved": 0
    },
    {
        "id": 2,
        "title": "обед",
        "text": "Вышел на обед",
        "color": "#ffc582",
        "icon": "AppleOutlined",
        "need_work": 2,
        "need_approved": 0
    },
    {
        "id": 3,
        "title": "перерыв",
        "text": "Вышел на перерыв",
        "color": "#fae5a9",
        "icon": "RestOutlined",
        "need_work": 2,
        "need_approved": 0
    },
    {
        "id": 4,
        "title": "на месте",
        "text": "На работе",
        "color": "#d0f5a5",
        "icon": "CheckOutlined",
        "need_work": null,
        "need_approved": 0
    },
    {
        "id": 5,
        "title": "ушел",
        "text": "Рабочий день закончен",
        "color": "#e4e4e4",
        "icon": "SafetyCertificateOutlined",
        "need_work": null,
        "need_approved": 0
    },
    {
        "id": 6,
        "title": "больничный",
        "text": "На больничном",
        "color": "#ffa8a8",
        "icon": "MedicineBoxOutlined",
        "need_work": 0,
        "need_approved": 0
    },
    {
        "id": 7,
        "title": "командировк.",
        "text": "Длительная командировка",
        "color": "#e2b4e9",
        "icon": "RocketOutlined",
        "need_work": 0,
        "need_approved": 0
    },
    {
        "id": 8,
        "title": "местн.выезд.",
        "text": "Кратковременная местная командировка",
        "color": "#e3dbf1",
        "icon": "CarOutlined",
        "need_work": 0,
        "need_approved": 0
    },
    {
        "id": 9,
        "title": "св.отпуск",
        "text": "Отпуск за свой счёт",
        "color": "#c4e8e5",
        "icon": "MoonOutlined",
        "need_work": 1,
        "need_approved": 0
    },
    {
        "id": 10,
        "title": "отпуск",
        "text": "Плановый отпуск",
        "color": "#7adfd6",
        "icon": "SmileOutlined",
        "need_work": 0,
        "need_approved": 0
    },
    {
        "id": 11,
        "title": "сверхурочные",
        "text": "Работа вне установленного графиком рабочего времени",
        "color": "#00ff97",
        "icon": "DollarOutlined",
        "need_work": 3,
        "need_approved": 0
    },
    {
        "id": 12,
        "title": "опоздание",
        "text": "Опоздания на работу или выход раньше установленных границ рабочего времени",
        "color": "#ddd7b5",
        "icon": "HeatMapOutlined",
        "need_work": 1,
        "need_approved": 0
    },
    {
        "id": 13,
        "title": "контейнеры",
        "text": "Разгрузка контейнеров на складе",
        "color": "#ffc107",
        "icon": "TruckOutlined",
        "need_work": 0,
        "need_approved": 0
    }
];


export const CLAIM_DEPARTS = [
    {
        "id": 1,
        "name": "Администрация",
        "rang": 1,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 2,
        "name": "Отдел персонала",
        "rang": 30,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 3,
        "name": "Бухгалтерия",
        "rang": 10,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 4,
        "name": "Техническая группа проектного отдела",
        "rang": 140,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 5,
        "name": "Отдел оптовых продаж",
        "rang": 50,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 6,
        "name": "Отдел рекламы",
        "rang": 70,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 7,
        "name": "Технический отдел трансляционного звука",
        "rang": 60,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 8,
        "name": "Проектный отдел",
        "rang": 100,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 9,
        "name": "Склад Санкт-Петербург",
        "rang": 120,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 11,
        "name": "Строительный отдел",
        "rang": 110,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 12,
        "name": "АХЧ",
        "rang": 200,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 13,
        "name": "Дилерский отдел",
        "rang": 130,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 14,
        "name": "Отдел информационных технологий",
        "rang": 90,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 15,
        "name": "Отдел информации",
        "rang": 40,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 17,
        "name": "Пулково КПП",
        "rang": 150,
        "visible": false,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 18,
        "name": "Пулково 19",
        "rang": 170,
        "visible": false,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 19,
        "name": "Контрагенты",
        "rang": 180,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 20,
        "name": "Технический отдел профессионального звука",
        "rang": 80,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    },
    {
        "id": 21,
        "name": "Отдел Логистики",
        "rang": 20,
        "visible": true,
        "deleted": false,
        "position": null,
        "icon": null
    }
];


export const CLAIMS_MOCKS = [
    {
        "id": 17,
        "user_id": 374,
        "start": "2025-05-20 00:00:00",
        "end": "2025-06-05 00:00:00",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 6,
        "deleted": 0,
        "state": 0,
        "info": "{\"description\":\"вафыва фы а фы ва фы ва ф ывафывафы вафы\"}",
        "days_count": 17,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:26:28",
        "created_at": "2025-05-14 17:26:28",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "больничный",
        "state_text": "На больничном",
        "state_icon": "MedicineBoxOutlined",
        "state_color": "#ffa8a8",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Евгений",
        "usr_surname": "Котоликов",
        "usr_patronymic": "Алексеевич",
        "depart_name": "Отдел оптовых продаж"
    },
    {
        "id": 16,
        "user_id": 272,
        "start": "2025-05-15 00:00:00",
        "end": "2025-05-15 00:00:00",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 13,
        "deleted": 0,
        "state": 0,
        "info": "{\"comment\":\"Таскать товары из машины в склад\"}",
        "days_count": 1,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:25:59",
        "created_at": "2025-05-14 17:25:59",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "контейнеры",
        "state_text": "Разгрузка контейнеров на складе",
        "state_icon": "TruckOutlined",
        "state_color": "#ffc107",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Фуркат",
        "usr_surname": "Ашуров  ",
        "usr_patronymic": "Пардакулович ",
        "depart_name": "Пулково 19"
    },
    {
        "id": 15,
        "user_id": 282,
        "start": "2025-05-15 00:00:00",
        "end": "2025-05-15 00:00:00",
        "data": null,
        "is_approved": 1,
        "approved_by": null,
        "skud_current_state_id": 13,
        "deleted": 0,
        "state": 0,
        "info": "{\"comment\":\"Таскать товары из машины в склад\"}",
        "days_count": 1,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:25:59",
        "created_at": "2025-05-14 17:25:59",
        "evaluated": 1,
        "evaluated_at": null,
        "state_title": "контейнеры",
        "state_text": "Разгрузка контейнеров на складе",
        "state_icon": "TruckOutlined",
        "state_color": "#ffc107",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Руслан",
        "usr_surname": "Шалин",
        "usr_patronymic": "Викторович",
        "depart_name": "Строительный отдел"
    },
    {
        "id": 14,
        "user_id": 283,
        "start": "2025-05-15 00:00:00",
        "end": "2025-05-15 00:00:00",
        "data": null,
        "is_approved": 1,
        "approved_by": null,
        "skud_current_state_id": 13,
        "deleted": 0,
        "state": 0,
        "info": "{\"comment\":\"Таскать товары из машины в склад\"}",
        "days_count": 1,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:25:59",
        "created_at": "2025-05-14 17:25:59",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "контейнеры",
        "state_text": "Разгрузка контейнеров на складе",
        "state_icon": "TruckOutlined",
        "state_color": "#ffc107",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Жанна",
        "usr_surname": "Булгакова",
        "usr_patronymic": "Владимировна",
        "depart_name": "Строительный отдел"
    },
    {
        "id": 13,
        "user_id": 272,
        "start": "2025-05-14 17:17:57",
        "end": "2025-05-31 17:17:57",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 13,
        "deleted": 0,
        "state": 0,
        "info": "{\"comment\":\"Таскать товары из машины в склад\"}",
        "days_count": 17,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:25:53",
        "created_at": "2025-05-14 17:25:53",
        "evaluated": 1,
        "evaluated_at": null,
        "state_title": "контейнеры",
        "state_text": "Разгрузка контейнеров на складе",
        "state_icon": "TruckOutlined",
        "state_color": "#ffc107",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Фуркат",
        "usr_surname": "Ашуров  ",
        "usr_patronymic": "Пардакулович ",
        "depart_name": "Пулково 19"
    },
    {
        "id": 12,
        "user_id": 282,
        "start": "2025-05-14 17:17:57",
        "end": "2025-05-31 17:17:57",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 13,
        "deleted": 0,
        "state": 1,
        "info": "{\"comment\":\"Таскать товары из машины в склад\"}",
        "days_count": 17,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:25:53",
        "created_at": "2025-05-14 17:25:53",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "контейнеры",
        "state_text": "Разгрузка контейнеров на складе",
        "state_icon": "TruckOutlined",
        "state_color": "#ffc107",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Руслан",
        "usr_surname": "Шалин",
        "usr_patronymic": "Викторович",
        "depart_name": "Строительный отдел"
    },
    {
        "id": 11,
        "user_id": 283,
        "start": "2025-05-14 17:17:57",
        "end": "2025-05-31 17:17:57",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 13,
        "deleted": 0,
        "state": 0,
        "info": "{\"comment\":\"Таскать товары из машины в склад\"}",
        "days_count": 17,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:25:53",
        "created_at": "2025-05-14 17:25:53",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "контейнеры",
        "state_text": "Разгрузка контейнеров на складе",
        "state_icon": "TruckOutlined",
        "state_color": "#ffc107",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Жанна",
        "usr_surname": "Булгакова",
        "usr_patronymic": "Владимировна",
        "depart_name": "Строительный отдел"
    },
    {
        "id": 10,
        "user_id": 91,
        "start": "2025-05-14 17:17:57",
        "end": "2025-05-31 17:17:57",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 9,
        "deleted": 0,
        "state": 2,
        "info": "{\"reason\":\"Большая и мощная причина 2\"}",
        "days_count": 17,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:25:18",
        "created_at": "2025-05-14 17:25:18",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "св.отпуск",
        "state_text": "Отпуск за свой счёт",
        "state_icon": "MoonOutlined",
        "state_color": "#c4e8e5",
        "state.need_work": 1,
        "state.need_approved": 0,
        "usr_name": "Сергей",
        "usr_surname": "Фокин",
        "usr_patronymic": "Петрович",
        "depart_name": "Технический отдел трансляционного звука"
    },
    {
        "id": 9,
        "user_id": 180,
        "start": "2025-05-14 17:17:57",
        "end": "2025-05-31 17:17:57",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 9,
        "deleted": 0,
        "state": 0,
        "info": "{\"reason\":\"Большая и мощная причина\"}",
        "days_count": 17,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 17:25:06",
        "created_at": "2025-05-14 17:25:06",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "св.отпуск",
        "state_text": "Отпуск за свой счёт",
        "state_icon": "MoonOutlined",
        "state_color": "#c4e8e5",
        "state.need_work": 1,
        "state.need_approved": 0,
        "usr_name": "Леонид",
        "usr_surname": "Александров",
        "usr_patronymic": "Алексеевич",
        "depart_name": "Склад Санкт-Петербург"
    },
    {
        "id": 8,
        "user_id": 57,
        "start": "2025-05-14 13:20:34",
        "end": "2025-05-14 13:20:34",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 11,
        "deleted": 0,
        "state": 0,
        "info": "{\"task\":\"Vyjufasjdfk jaslkdfasdf\",\"result\":\"fasdf asdfasdfasdfasd\"}",
        "days_count": 1,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 13:20:55",
        "created_at": "2025-05-14 13:20:55",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "сверхурочные",
        "state_text": "Работа вне установленного графиком рабочего времени",
        "state_icon": "DollarOutlined",
        "state_color": "#b7ff5c",
        "state.need_work": 3,
        "state.need_approved": 0,
        "usr_name": "Дмитрий",
        "usr_surname": "Печников",
        "usr_patronymic": "Валерьевич",
        "depart_name": "Отдел оптовых продаж"
    },
    {
        "id": 7,
        "user_id": 46,
        "start": "2025-05-14 12:20:47",
        "end": "2025-05-17 12:20:47",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 8,
        "deleted": 0,
        "state": 0,
        "info": "{\"target_point\":\"\\\"Архангельск \\\\?|\\\"\",\"target_address\":\"Город Ангелов\\/\",\"contact_person\":\"Зубенко Михаил Петрович\",\"contact_phone\":\"425435234523\",\"comment\":\"#Большой и жирный комментарий нам в кассу.\",\"subway_count\":7,\"bus_count\":7}",
        "days_count": 3,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 12:44:37",
        "created_at": "2025-05-14 12:44:37",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "местн.выезд.",
        "state_text": "Кратковременная местная командировка",
        "state_icon": "CarOutlined",
        "state_color": "#e3dbf1",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Александр",
        "usr_surname": "Кошелев",
        "usr_patronymic": "Станиславович",
        "depart_name": "Администрация"
    },
    {
        "id": 6,
        "user_id": 46,
        "start": "2025-05-14 12:20:47",
        "end": "2025-05-17 12:20:47",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 8,
        "deleted": 0,
        "state": 0,
        "info": "{\"target_point\":\"Архангельск \\\\?|\",\"target_address\":\"Город Ангелов\\/\",\"contact_person\":\"Зубенко Михаил Петрович\",\"contact_phone\":\"425435234523\",\"comment\":\"#Большой и жирный комментарий нам в кассу.\",\"subway_count\":7,\"bus_count\":7}",
        "days_count": 3,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 12:44:22",
        "created_at": "2025-05-14 12:44:22",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "местн.выезд.",
        "state_text": "Кратковременная местная командировка",
        "state_icon": "CarOutlined",
        "state_color": "#e3dbf1",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Александр",
        "usr_surname": "Кошелев",
        "usr_patronymic": "Станиславович",
        "depart_name": "Администрация"
    },
    {
        "id": 5,
        "user_id": 46,
        "start": "2025-05-14 12:20:47",
        "end": "2025-05-17 12:20:47",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 8,
        "deleted": 0,
        "state": 0,
        "info": "{\"target_point\":\"Архангельск \\\\?|\",\"target_address\":\"Город Ангелов\",\"contact_person\":\"Зубенко Михаил Петрович\",\"contact_phone\":\"425435234523\",\"comment\":\"#Большой и жирный комментарий нам в кассу.\",\"subway_count\":7,\"bus_count\":7}",
        "days_count": 3,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 12:44:06",
        "created_at": "2025-05-14 12:44:06",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "местн.выезд.",
        "state_text": "Кратковременная местная командировка",
        "state_icon": "CarOutlined",
        "state_color": "#e3dbf1",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Александр",
        "usr_surname": "Кошелев",
        "usr_patronymic": "Станиславович",
        "depart_name": "Администрация"
    },
    {
        "id": 4,
        "user_id": 46,
        "start": "2025-05-14 12:20:47",
        "end": "2025-05-17 12:20:47",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 8,
        "deleted": 0,
        "state": 0,
        "info": "{\"target_point\":\"Архангельск\",\"target_address\":\"Город Ангелов\",\"contact_person\":\"Зубенко Михаил Петрович\",\"contact_phone\":\"425435234523\",\"comment\":\"#Большой и жирный комментарий нам в кассу.\\nА что, если сюда записать разные спецсимволы?$$value Hello&\",\"subway_count\":7,\"bus_count\":7}",
        "days_count": 3,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 12:43:34",
        "created_at": "2025-05-14 12:43:34",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "местн.выезд.",
        "state_text": "Кратковременная местная командировка",
        "state_icon": "CarOutlined",
        "state_color": "#e3dbf1",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Александр",
        "usr_surname": "Кошелев",
        "usr_patronymic": "Станиславович",
        "depart_name": "Администрация"
    },
    {
        "id": 3,
        "user_id": 91,
        "start": "2025-05-14 12:20:47",
        "end": "2025-05-17 12:20:47",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 8,
        "deleted": 0,
        "state": 0,
        "info": "{\"target_point\":\"Архангельск\",\"target_address\":\"Город Ангелов\",\"contact_person\":\"Зубенко Михаил Петрович\",\"contact_phone\":\"425435234523\",\"comment\":\"Большой и жирный комментарий нам в кассу\",\"subway_count\":7,\"bus_count\":7}",
        "days_count": 3,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 12:42:08",
        "created_at": "2025-05-14 12:42:08",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "местн.выезд.",
        "state_text": "Кратковременная местная командировка",
        "state_icon": "CarOutlined",
        "state_color": "#e3dbf1",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Сергей",
        "usr_surname": "Фокин",
        "usr_patronymic": "Петрович",
        "depart_name": "Технический отдел трансляционного звука"
    },
    {
        "id": 2,
        "user_id": 91,
        "start": "2025-05-14 12:20:47",
        "end": "2025-05-17 12:20:47",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 8,
        "deleted": 0,
        "state": 0,
        "info": "{\"target_point\":\"\\u0410\\u0440\\u0445\\u0430\\u043d\\u0433\\u0435\\u043b\\u044c\\u0441\\u043a\",\"target_address\":\"\\u0413\\u043e\\u0440\\u043e\\u0434 \\u0410\\u043d\\u0433\\u0435\\u043b\\u043e\\u0432\",\"contact_person\":\"\\u0417\\u0443\\u0431\\u0435\\u043d\\u043a\\u043e \\u041c\\u0438\\u0445\\u0430\\u0438\\u043b \\u041f\\u0435\\u0442\\u0440\\u043e\\u0432\\u0438\\u0447\",\"contact_phone\":\"425435234523\",\"comment\":\"\\u0411\\u043e\\u043b\\u044c\\u0448\\u043e\\u0439 \\u0438 \\u0436\\u0438\\u0440\\u043d\\u044b\\u0439 \\u043a\\u043e\\u043c\\u043c\\u0435\\u043d\\u0442\\u0430\\u0440\\u0438\\u0439 \\u043d\\u0430\\u043c \\u0432 \\u043a\\u0430\\u0441\\u0441\\u0443\",\"subway_count\":7,\"bus_count\":7}",
        "days_count": 3,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 12:32:18",
        "created_at": "2025-05-14 12:32:18",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "местн.выезд.",
        "state_text": "Кратковременная местная командировка",
        "state_icon": "CarOutlined",
        "state_color": "#e3dbf1",
        "state.need_work": 0,
        "state.need_approved": 0,
        "usr_name": "Сергей",
        "usr_surname": "Фокин",
        "usr_patronymic": "Петрович",
        "depart_name": "Технический отдел трансляционного звука"
    },
    {
        "id": 1,
        "user_id": 134,
        "start": "2025-05-14 12:20:47",
        "end": "2025-05-17 12:20:47",
        "data": null,
        "is_approved": 0,
        "approved_by": null,
        "skud_current_state_id": 9,
        "deleted": 0,
        "state": 0,
        "info": "{\"reason\":\"I want to otpusk\"}",
        "days_count": 3,
        "approver_id": null,
        "approved_date": null,
        "updated_at": "2025-05-14 12:30:42",
        "created_at": "2025-05-14 12:30:42",
        "evaluated": 0,
        "evaluated_at": null,
        "state_title": "св.отпуск",
        "state_text": "Отпуск за свой счёт",
        "state_icon": "MoonOutlined",
        "state_color": "#c4e8e5",
        "state.need_work": 1,
        "state.need_approved": 0,
        "usr_name": "Сергей",
        "usr_surname": "Безбородов",
        "usr_patronymic": "Дмитриевич",
        "depart_name": "Отдел оптовых продаж"
    }
]


export const CLAIM_ACL_MOCK = {
    "2": {
        "6": [
            "ANY_CLAIM_APPROVE",
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "7": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "8": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "9": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "10": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "11": [
            "TEAM_CLAIM_UPDATE",
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "13": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ]
    },
    "3": {
        "6": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "7": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "8": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "9": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "10": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "11": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ],
        "13": [
            "PERS_CLAIM_CREATE",
            "PERS_CLAIM_UPDATE",
            "PERS_CLAIM_APPROVE",
            "TEAM_CLAIM_CREATE",
            "TEAM_CLAIM_UPDATE",
            "TEAM_CLAIM_APPROVE",
            "ANY_CLAIM_CREATE",
            "ANY_CLAIM_UPDATE",
            "ANY_CLAIM_APPROVE"
        ]
    }
}

// export const CLAIM_BASE_CLAIM_TYPES = [
//     {
//         key: 'clt_9',
//         value: 9, 
//         label: 'Отпуск за свой счёт',
//         icon: <MoonOutlined />
//     },
//     {
//         key: 'clt_8',
//         value: 8, 
//         label: 'Кратковременная командировка',
//         icon: <CarOutlined />
//     },
//     {
//         key: 'clt_7',
//         value: 7, 
//         label: 'Длительная командировка',
//         icon: <RocketOutlined />
//     },
//     {
//         key: 'clt_10',
//         value: 10, 
//         label: 'Отпуск',
//         icon: <SmileOutlined />
//     },
//     {
//         key: 'clt_11',
//         value: 11, 
//         label: 'Сверхурочные',
//         icon: <DollarOutlined />
//     },
//     {
//         key: 'clt_6',
//         value: 6, 
//         label: 'Больничные',
//         icon: <MedicineBoxOutlined />
//     },
//     {
//         key: 'clt_13',
//         value: 13, 
//         label: 'Контейнеры',
//         icon: <TruckOutlined />
//     }
// ];

export const CLAIM_BASE_CLAIM_TYPES = [
    {
        "id": 9,
        "badge": "св.отпуск",
        "text": "Отпуск за свой счёт",
        "color": "#c4e8e5",
        "icon": "MoonOutlined",
        "need_work": 1,
        "need_approved": 0,
        "sort_order": 1,
        "fillable": 1,
        "title": "Отпуск за свой счёт"
    },
    {
        "id": 8,
        "badge": "местн.выезд.",
        "text": "Кратковременная местная командировка",
        "color": "#e3dbf1",
        "icon": "CarOutlined",
        "need_work": 0,
        "need_approved": 0,
        "sort_order": 2,
        "fillable": 1,
        "title": "Местная командировка"
    },
    {
        "id": 7,
        "badge": "командировк.",
        "text": "Длительная командировка",
        "color": "#e2b4e9",
        "icon": "RocketOutlined",
        "need_work": 0,
        "need_approved": 0,
        "sort_order": 3,
        "fillable": 1,
        "title": "Командировка длительная"
    },
    {
        "id": 10,
        "badge": "отпуск",
        "text": "Плановый отпуск",
        "color": "#7adfb8",
        "icon": "SmileOutlined",
        "need_work": 0,
        "need_approved": 0,
        "sort_order": 4,
        "fillable": 1,
        "title": "Очередные отпуска"
    },
    {
        "id": 11,
        "badge": "сверхурочные",
        "text": "Работа вне установленного графиком рабочего времени",
        "color": "#b7ff5c",
        "icon": "DollarOutlined",
        "need_work": 3,
        "need_approved": 0,
        "sort_order": 5,
        "fillable": 1,
        "title": "Сверхурочные"
    },
    {
        "id": 6,
        "badge": "больничный",
        "text": "На больничном",
        "color": "#ffa8a8",
        "icon": "MedicineBoxOutlined",
        "need_work": 0,
        "need_approved": 0,
        "sort_order": 6,
        "fillable": 1,
        "title": "Больничные"
    },
    {
        "id": 13,
        "badge": "контейнеры",
        "text": "Разгрузка контейнеров на складе",
        "color": "#ffc107",
        "icon": "TruckOutlined",
        "need_work": 0,
        "need_approved": 0,
        "sort_order": 7,
        "fillable": 1,
        "title": "Разгрузка контейнеров"
    }
]

// const typeOptions = [
//   {
//     value: 0,
//     label: 'Все заявки',
//     icon: <BlockOutlined />,
//     background: '#c3c3c3'
//   },
//   {
//     value: 9,
//     label: 'Отпуск СВ',
//     icon: <MoonOutlined />,
//     background: '#c4e8e5'
//   },
//   {
//     value: 8,
//     label: 'Крат. ком.',
//     icon: <CarOutlined />,
//     background: '#e3dbf1'
//   },
//   {
//     value: 7,
//     label: 'Длит. ком.',
//     icon: <RocketOutlined />,
//     background: '#e2b4e9'
//   },
//   {
//     value: 10,
//     label: 'Отпуск',
//     icon: <SmileOutlined />,
//     background: '#7adfb8'
//   },
//   {
//     value: 11,
//     label: 'Сверхурочн.',
//     icon: <DollarOutlined />,
//     background: '#b7ff5c'
//   },
//   {
//     value: 6,
//     label: 'Больничн.',
//     icon: <MedicineBoxOutlined />,
//     background: '#ffa8a8'
//   },
//   {
//     value: 13,
//     label: 'Контейн.',
//     icon: <DockerOutlined />,
//     background: '#ffc107'
//   }
// ];