import { AppleOutlined, CarOutlined, CheckOutlined, MedicineBoxOutlined, MinusCircleOutlined, MoonOutlined, PictureOutlined, RestOutlined, RocketOutlined, SafetyCertificateOutlined, SmileOutlined } from "@ant-design/icons"

export const OPENMODE = {
    READ: 0,
    EDIT: 10,
    SHORTEDIT: 11,
    AFTERCREATE: 15,
    CREATE: 20
}

export const DEF_SCHEDULE = {
    "id": null,
    "id_company": null,
    "company_name": null,
    "company_color": null,
    "skud_schedule_type_id": 1,
    "name": null,
    "description": "",
    "start_time": 33300,
    "end_time": 64800,
    "target_time": (60*60*8),
    "target_unit": 1,
    "lunch_start": 46800,
    "lunch_end": 54000,
    "lunch_time": (2700),
    "schedule": [],
    "next_id": null,
    "deleted": 0,
    "skud_prod_calendar_id": null,
    "created_at": null,
    "creator_id": null
}

export const BASE_CLAIM_TYPES = [
    {
        "id": 1,
        "badge": "",
        "text": "Не приходил в офис",
        "color": "#fefefe",
        "icon": "MinusCircleOutlined",
        "need_work": 1,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 2,
        "badge": "обед",
        "text": "Вышел на обед",
        "color": "#ffc582",
        "icon": "AppleOutlined",
        "need_work": 2,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 3,
        "badge": "перерыв",
        "text": "Вышел на перерыв",
        "color": "#fae5a9",
        "icon": "RestOutlined",
        "need_work": 2,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 4,
        "badge": "на месте",
        "text": "На работе",
        "color": "#d0f5a5",
        "icon": "CheckOutlined",
        "need_work": null,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 5,
        "badge": "ушел",
        "text": "Рабочий день закончен",
        "color": "#e4e4e4",
        "icon": "SafetyCertificateOutlined",
        "need_work": null,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 12,
        "badge": "опоздание",
        "text": "Опоздания на работу или выход раньше установленных границ рабочего времени",
        "color": "#ddd7b5",
        "icon": "HeatMapOutlined",
        "need_work": 1,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 14,
        "badge": "рабоч. время.",
        "text": "рабочее время",
        "color": "#85FF93",
        "icon": "CheckOutlined",
        "need_work": null,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 15,
        "badge": "ранний приход",
        "text": "пришел раньше",
        "color": "#85E7FF",
        "icon": "LoginOutlined",
        "need_work": null,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 16,
        "badge": "опоздание",
        "text": "опоздал",
        "color": "#FFC085",
        "icon": "WarningOutlined",
        "need_work": 1,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 17,
        "badge": "отработка ПВ",
        "text": "рабочее время для отработки ПВ",
        "color": "#0077EE",
        "icon": "FireOutlined",
        "need_work": 1,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 18,
        "badge": "ранний уход",
        "text": "ушел раньше",
        "color": "#FFC085",
        "icon": "ExlamationCircleOutlined",
        "need_work": 1,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 19,
        "badge": "поздн. уход",
        "text": "ушел позже",
        "color": "#85E7FF",
        "icon": "Logoutoutlined",
        "need_work": null,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 20,
        "badge": "обед. перерыв.",
        "text": "обеденное время",
        "color": "#85A3FF",
        "icon": "JavaOutlined",
        "need_work": null,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 21,
        "badge": "своб. выход",
        "text": "Свободный выход на перерыв",
        "color": "#b7a882",
        "icon": "TwitterOutlined",
        "need_work": 0,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 22,
        "badge": "накопление вр.",
        "text": "рабочее время для накопления запаса времени",
        "color": "#447799",
        "icon": "GoldOutlined",
        "need_work": null,
        "need_approved": 0,
        "sort_order": 0,
        "title": null,
        "name": null,
        "fillable": 0
    },
    {
        "id": 8,
        "badge": "местн.команд.",
        "text": "Кратковременная местная командировка",
        "color": "#95bbcd",
        "icon": "CarOutlined",
        "need_work": 0,
        "need_approved": 1,
        "sort_order": 1,
        "title": "Местная командировка",
        "name": "shorttrip",
        "fillable": 1
    },
    {
        "id": 9,
        "badge": "неопл.отпуск",
        "text": "Отпуск за свой счёт",
        "color": "#cbb9a2",
        "icon": "MoonOutlined",
        "need_work": 1,
        "need_approved": 1,
        "sort_order": 2,
        "title": "Неоплачиваемый отпуск",
        "name": "shortvacation",
        "fillable": 1
    },
    {
        "id": 11,
        "badge": "сверхурочные",
        "text": "Работа вне установленного графиком рабочего времени",
        "color": "#81e59b",
        "icon": "DollarOutlined",
        "need_work": 3,
        "need_approved": 1,
        "sort_order": 3,
        "title": "Сверхурочные",
        "name": "overtime",
        "fillable": 1
    },
    {
        "id": 7,
        "badge": "командировка",
        "text": "Длительная командировка",
        "color": "#ff996a",
        "icon": "RocketOutlined",
        "need_work": 0,
        "need_approved": 1,
        "sort_order": 4,
        "title": "Командировка",
        "name": "longtrip",
        "fillable": 1
    },
    {
        "id": 10,
        "badge": "отпуск",
        "text": "Плановый отпуск",
        "color": "#7adcdf",
        "icon": "SmileOutlined",
        "need_work": 0,
        "need_approved": 1,
        "sort_order": 5,
        "title": "Отпуск",
        "name": "longvacation",
        "fillable": 1
    },
    {
        "id": 6,
        "badge": "больничнный",
        "text": "Больничный",
        "color": "#ffa8a8",
        "icon": "MedicineBoxOutlined",
        "need_work": 0,
        "need_approved": 0,
        "sort_order": 6,
        "title": "Больничнный",
        "name": "sickleave",
        "fillable": 1
    },
    {
        "id": 13,
        "badge": "контейнеры",
        "text": "Разгрузка контейнеров на складе",
        "color": "#e3d97c",
        "icon": "TruckOutlined",
        "need_work": 0,
        "need_approved": 1,
        "sort_order": 7,
        "title": "Контейнеры",
        "name": "containers",
        "fillable": 1
    }
];

// текущее состояние юзера - 0 - нет и не был, 4 - вышел на обед, 10 - на работе, 5 - вышел на перерыв, 20 - ушел с работы, 30 - больняки
export   const USER_STATE_PLACES = {
    0: { title: "Не приходил в офис", text: "", color: "#fefefe", icon: <MinusCircleOutlined />},
    4: { title: "Вышел на обед", text: "обед", color: "#ffc582", icon:<AppleOutlined /> },
    5: { title: "Вышел на перерыв", text: "перерыв", color: "#fae5a9", icon: <RestOutlined />},
    10: { title: "На работе", text: "на месте", color: "#d0f5a5", icon: <CheckOutlined />},
    20: { title: "Рабочий день закончен", text: "ушел", color: "#e4e4e4", icon: <SafetyCertificateOutlined />},
    30: { title: "На больничном", text: "больничный", color: "#ffa8a8", icon: <MedicineBoxOutlined /> },
    45: { title: "Длительная командировка", text: "командировк.", color: "#e2b4e9", icon: <RocketOutlined />},
    40: { title: "Кратковременная локальная командировка", text: "местн.выезд", color: "#e3dbf1", icon: <CarOutlined /> },
    50: { title: "Отпуск за свой счёт", text: "св.отпуск", color: "#c4e8e5", icon: <MoonOutlined /> },
    55: { title: "Плановый отпуск", text: "отпуск", color: "#7adfd6", icon: <SmileOutlined /> },
}